version: '3'
services:
    db:
        image: postgres:10.5-alpine
        volumes:
            - dbdata:/data/db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
volumes:
    ? dbdata
